version: '3'
services:
    gamex_nginx:
        image: nginx:stable-alpine
        environment:
            NGINX_HOST: localhost
        ports:
            - "18001:80"
        volumes:
            - ./app:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - gamex_php
    gamex_php:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - ./app:/app
        links:
            - gamex_db
    gamex_db:
        image: mysql:5.7.22
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        environment:
            MYSQL_DATABASE: gamex
            MYSQL_USER: gamex
            MYSQL_PASSWORD: gamex
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 13306:3306
        volumes:
            - ./database:/var/lib/mysql